#!/usr/bin/env bash
#Script that uses a while loop and if statement to display a piece of text
y=1
while [ $y -le 10 ]
do
  echo "Best School"
  if [ $y -eq 9 ]
  then
      echo "Hi"
  fi
  ((y++))
done
