#!/usr/bin/env bash
#Script that uses case statements
y=1
while [ $y -le 20 ]
do
  echo "$y"
  case $y in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
  esac
  ((y++))
done
